### ISSUE TITLE
OutputPath is not mandatory but the script expects it to be specified

### ISSUE THREAD

**Issue by mattallford** [AsBuiltReport/AsBuiltReport#19]
**Describe the bug**
The parameter -OutputPath on New-AsBuiltReport is not currently a mandatory parameter, but attempting to run the cmdlet without this parameter will result in a failure, as it does not have a path to export the document to.

**To Reproduce**
1. Run New-AsBuiltReport without specifying the -OutputPath Parameter. This will result in an error "New-AsBuiltReport: Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that is not null or empty and then try the command again."

**Expected behavior**
I expected to be prompted on where to save the report, or have a default folder where reports will be saved to.

**Desktop (please complete the following information):**
Not relevant

**Comment by tpcarman** [comment]
Resolved issue in 9298ff64b4936074e5edd05537a7aac0a2edb70e
