### ISSUE TITLE
Update report module manifests to clearly describe the dependency for AsBuiltReport module

### ISSUE THREAD

**Issue by tpcarman** [AsBuiltReport/AsBuiltReport#21]
When searching the PowerShell Gallery, users may believe that they can download and use report modules independently of the base AsBuiltReport module.

Report manifests should be updated to document the dependency of the AsBuiltReport base module.

**Comment by mc1903** [comment]
Talking of the AsBuiltReport base module, surly **only** PScribo is actually required? 

What's the rationale for making the report modules themselves a requirement of the base module? This just serves to install every report module whether you want it or not?

![image](https://user-images.githubusercontent.com/13692287/54999215-a95c5e80-4fc7-11e9-86a8-27575fec87b9.png)

Q. Everytime a new report module is released, will the base module manifest be updated to make the new report module required? Seems like a lot of work if yes.

M

**Comment by tpcarman** [comment]
I’ll let @mattallford answer this one.

**Comment by mattallford** [comment]
@mc1903 You are correct in saying that truly only PScribo is _required_, but as you said we want to ensure that users get access to all of the reports without having to:
a) Do more work to know about the reports that are released and go looking for them
b) Download the base AsBuiltReport and then get confused as to why they can't run any reports

I'm open to changing this as we get more reports and as the project grows if it becomes an issue, but one of our key project goals is simplicity and I think that by making all released report modules a required module for AsBuiltReport, it makes it very simple for the user, for now.

This is similar to the concept that PowerCLI or Azure modules follow, and many other for that matter. If you install PowerCLI, you end up with about 15 different modules, some of which you may never even use.

Yep, every time a new report module is released, the base module manifest needs to be updated to include the new report module as a required module. This is probably a 10 minute change to PR to GitHub and then update the PSGallery, so unless we see a huge uptake in report creations, this likely isn't a big deal. Realistically we'll probably see one or two new reports added per month, at best.

**Comment by tpcarman** [comment]
After further discussions with @mattallford today, I believe we now have a solution, however we need to test it.

- We will create a new module called `AsBuiltReport.Core`. This module will be the base module containing the functions to generate reports and include `RequiredModules` for PScribo. 
- The `AsBuiltReport` module will become a manifest with `RequireModules` for `AsBuiltReport.Core` and *all* available report modules. 
- Report modules will include `RequiredModules` for `AsBuiltReport.Core`.

This should then allow users to choose between installing everything via `Install-Module AsBuiltReport` or installing reports individually e.g. `Install-Module AsBuiltReport.VMware.vSphere`

**Comment by mc1903** [comment]
@tpcarman @mattallford Elegant solution. I very much like. Thankyou.

Will the `RequiredModules` for each of the report modules be limited to just `AsBuiltReport.Core`?

I understand the current requirement is to manually install 3rd party modules (i.e. `PowerCLI` , `PureStoragePowerShellSDK`, etc.), but is there any situation in which you might consider allowing these to be included as `RequiredModules` within the manifest for a given report module?

**Comment by tpcarman** [comment]
No. It was something we agreed early on. It will cause too many issues, so we rely on the user to pre-install  3rd party modules.
It it important to understand that not all 3rd parties share their cmdlets/modules via the PowerShell Gallery.

**Comment by tpcarman** [comment]
Resolved in https://github.com/AsBuiltReport/AsBuiltReport/commit/274512d6f7f4bf44724fef6c2c712b5017d6dcc7
